services:
  scrapify:
    container_name: scrapify_client_dev
    image: scrapify_client_dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 4545:3000
    environment:
      - CHOKIDAR_USEPOLLING=true